import type { Metadata } from "next";
import "./globals.css";
import { Inter, Noto_Kufi_Arabic } from "next/font/google";
import useTranslation from "next-translate/useTranslation";

const inter = Inter({
  subsets: ["latin"],
});
const notoKufiArabic = Noto_Kufi_Arabic({
  subsets: ["arabic"],
});

export const metadata: Metadata = {
  title: "Style Sheet",
  description: "Generated by create Eq",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { lang } = useTranslation("common");
  const isArabic = lang === "ar";
  const direction = isArabic ? "rtl" : "ltr";
  const textAlign = isArabic ? "text-right" : "text-left";
  const fontClass = isArabic ? notoKufiArabic.className : inter.className;

  return (
    <html lang="en">
      <body
        className={`${fontClass} bg-white text-black ${direction} ${textAlign}`}
      >
        {children}
      </body>
    </html>
  );
}
